### ISSUE TITLE
Auto slider

### ISSUE THREAD

**Issue by ytfahmed** [bootscore/bs-swiper#1]
This and the other themes and plugins are amazing, and we really appreciate the work you have been doing.
Is there any way to implement auto sliding? Or maybe using the Bootstrap carousel but for multiple posts per slider.

Thanks.

**Comment by craftwerkberlin** [comment]
Thank you!

There are 2 templates, cards and hero. Hero slider has autoplay. Maybe I add a new card template for autoslide cards. But for now if you want to use autoslide in card template you can set init to

`               autoplay: {
                    delay: 4000,
                },`

in swiper-init.js.

When doing this, delete folder update in root folder, open main.php and delete snippet from line 12 to 18. Otherwise your changes will be lost by new update. Check the docs https://bootscore.me/documentation/bs-swiper/ for using the plugin templates.

Does that help?

**Comment by ytfahmed** [comment]
Thanks I will check it.
