### ISSUE TITLE
Multiple sliders on one page

### ISSUE THREAD

**Issue by artinflight** [bootscore/bs-swiper#8]
I've got two sliders on one page, one is showing posts and another a custom post type. When I slide one it slides both of them, is there a way to fix this?

		 [bs-swiper-card type="video" order="DESC" orderby="date"]
		 [bs-swiper-card type="post" order="DESC" orderby="date"]

Thanks in advance!

**Comment by crftwrk** [comment]
Please share a link to your sliders to check.

BTW your shortcodes are not complete. You selected which type you want to show but not which category or taxonomy. These are mandatory to get plugin work properly. Maybe your issue is because they are missing.

Check here for shortcode examples https://bootscore.me/documentation/bs-swiper/

**Comment by artinflight** [comment]
> Please share a link to your sliders to check.
> 
> BTW your shortcodes are not complete. You selected which type you want to show but not which category or taxonomy. These are mandatory to get plugin work properly. Maybe your issue is because they are missing.
> 
> Check here for shortcode examples https://bootscore.me/documentation/bs-swiper/

Oddly enough they are working now, I had disabled the controls for the posts slider. Maybe that is why they were tied together. I re-enabled the slider controls and now both are working fine. We can mark this issue as closed.

**Comment by crftwrk** [comment]
👍
